// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NTier.Persistence.Entities
{
    public partial class TodoItem
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public int TodoListId { get; set; }
        public DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }

        public virtual TodoList TodoList { get; set; }
    }
}